CREATE TABLE IF NOT EXISTS feeds (
  id serial primary key,
  customer_id int REFERENCES customers(id),
  title text,
  description text,
  generator text,
  feed_url text,
  site_url text,
  image_url text,
  docs text,
  author text,
  managing_editor text,
  web_master text,
  copyright text,
  language text,
  categories text[],
  pub_date date,
  ttl int,
  itunes_author text,
  itunes_subtitle text,
  itunes_summary text,
  itunes_owner text,
  itunes_explicit text,
  itunes_category text[],
  itunes_image text
);
